import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
import {
  DEFAULT_TERMS_CONTENT,
  DEFAULT_TERMS_TITLE,
  DEFAULT_TERMS_VERSION,
} from "../src/lib/default-terms";

const prisma = new PrismaClient();

async function main() {
  const password = await bcrypt.hash("demo1234", 10);

  const demoUsers = [
    {
      email: "amina@demo.com",
      firstName: "Amina",
      profile: {
        gender: "Femme",
        seekingGender: "Hommes",
        age: 28,
        height: 165,
        profession: "Architecte d'intérieur",
        religion: "Sincérité, humour et projet de famille",
        origin: "Sénégalaise",
        maritalStatus: "Jamais marié(e)",
        location: "Paris",
        bio: "Je cherche quelqu'un de stable, drôle et prêt à construire quelque chose de beau ensemble.",
        qualities: JSON.stringify(["À l'écoute", "Drôle", "Ambitieux(se)"]),
        seekingAgeMax: 35,
        seekingHeightMax: 190,
        seekingProfession: "Situation stable",
        seekingReligion: "Bienveillance et sincérité",
        seekingOrigin: "Peu importe",
        seekingMaritalStatus: "Jamais marié(e)",
        seekingLocation: "Paris",
        completionPct: 100,
        completed: true,
      },
    },
    {
      email: "youssef@demo.com",
      firstName: "Youssef",
      profile: {
        gender: "Homme",
        seekingGender: "Femmes",
        age: 31,
        height: 180,
        profession: "Ingénieur logiciel",
        religion: "Respect, communication et stabilité",
        origin: "Marocain",
        maritalStatus: "Jamais marié(e)",
        location: "Lyon",
        bio: "Passionné de voyages et de bonne cuisine. Je cherche ma complice pour la vie.",
        qualities: JSON.stringify(["Bienveillant(e)", "Sportif(ve)", "Patient(e)"]),
        seekingAgeMax: 32,
        seekingHeightMax: 175,
        seekingProfession: "Peu importe",
        seekingReligion: "Maturité et envie de construire",
        seekingOrigin: "Peu importe",
        seekingMaritalStatus: "Peu importe",
        seekingLocation: "Lyon",
        completionPct: 100,
        completed: true,
      },
    },
    {
      email: "sophie@demo.com",
      firstName: "Sophie",
      profile: {
        gender: "Femme",
        seekingGender: "Femmes",
        age: 32,
        height: 168,
        profession: "Professeure des écoles",
        religion: "Famille, confiance et simplicité",
        origin: "Française",
        maritalStatus: "Jamais marié(e)",
        location: "Bordeaux",
        bio: "J'aime les balades, la lecture et les dimanches en famille.",
        qualities: JSON.stringify(["Cultivé(e)", "Familial(e)", "Fidèle"]),
        seekingAgeMax: 38,
        seekingHeightMax: 190,
        seekingProfession: "Situation stable",
        seekingReligion: "Sincérité et stabilité",
        seekingOrigin: "Peu importe",
        seekingMaritalStatus: "Jamais marié(e)",
        seekingLocation: "Bordeaux",
        completionPct: 100,
        completed: true,
      },
    },
    {
      email: "thomas@demo.com",
      firstName: "Thomas",
      profile: {
        gender: "Homme",
        seekingGender: "Les deux",
        age: 35,
        height: 182,
        profession: "Chef de projet",
        religion: "Honnêteté, complicité et projet commun",
        origin: "Français",
        maritalStatus: "Divorcé(e)",
        location: "Nantes",
        bio: "Deuxième chapitre, avec plus de maturité. Je cherche quelqu'un avec qui rire et avancer.",
        qualities: JSON.stringify(["Drôle", "Sportif(ve)", "Spontané(e)"]),
        seekingAgeMax: 40,
        seekingHeightMax: 175,
        seekingProfession: "Situation professionnelle stable",
        seekingReligion: "Maturité et bienveillance",
        seekingOrigin: "Peu importe",
        seekingMaritalStatus: "Peu importe",
        seekingLocation: "Nantes",
        completionPct: 100,
        completed: true,
      },
    },
    {
      email: "fatou@demo.com",
      firstName: "Fatou",
      profile: {
        gender: "Femme",
        seekingGender: "Hommes",
        age: 26,
        height: 163,
        profession: "Designer graphique",
        religion: "Créativité, respect et ambition",
        origin: "Camerounaise",
        maritalStatus: "Jamais marié(e)",
        location: "Paris",
        bio: "Amoureuse de l'art et des bonnes vibes. Je cherche un homme stable qui aime voyager.",
        qualities: JSON.stringify(["Créatif(ve)", "Ambitieux(se)", "Spontané(e)"]),
        seekingAgeMax: 34,
        seekingHeightMax: 190,
        seekingProfession: "Situation stable",
        seekingReligion: "Sincérité et humour",
        seekingOrigin: "Peu importe",
        seekingMaritalStatus: "Jamais marié(e)",
        seekingLocation: "Paris",
        completionPct: 100,
        completed: true,
      },
    },
    {
      email: "karim@demo.com",
      firstName: "Karim",
      profile: {
        gender: "Homme",
        seekingGender: "Femmes",
        age: 29,
        height: 178,
        profession: "Médecin généraliste",
        religion: "Empathie, famille et équilibre",
        origin: "Algérien",
        maritalStatus: "Jamais marié(e)",
        location: "Marseille",
        bio: "Entre garde à l'hôpital et coucher de soleil sur le Vieux-Port. Prêt pour un vrai projet.",
        qualities: JSON.stringify(["Bienveillant(e)", "Patient(e)", "Familial(e)"]),
        seekingAgeMax: 32,
        seekingHeightMax: 175,
        seekingProfession: "Peu importe",
        seekingReligion: "Bienveillance et maturité",
        seekingOrigin: "Peu importe",
        seekingMaritalStatus: "Jamais marié(e)",
        seekingLocation: "Marseille",
        completionPct: 100,
        completed: true,
      },
    },
    {
      email: "lea@demo.com",
      firstName: "Léa",
      profile: {
        gender: "Femme",
        seekingGender: "Femmes",
        age: 27,
        height: 170,
        profession: "Journaliste",
        religion: "Curiosité, authenticité et engagement",
        origin: "Ivoirienne",
        maritalStatus: "Jamais marié(e)",
        location: "Toulouse",
        bio: "J'écris, je voyage, je cuisine. À la recherche d'une connexion profonde et joyeuse.",
        qualities: JSON.stringify(["Cultivé(e)", "Drôle", "Indépendant(e)"]),
        seekingAgeMax: 35,
        seekingHeightMax: 185,
        seekingProfession: "Situation stable",
        seekingReligion: "Authenticité",
        seekingOrigin: "Peu importe",
        seekingMaritalStatus: "Peu importe",
        seekingLocation: "Toulouse",
        completionPct: 100,
        completed: true,
      },
    },
    {
      email: "david@demo.com",
      firstName: "David",
      profile: {
        gender: "Homme",
        seekingGender: "Femmes",
        age: 33,
        height: 185,
        profession: "Entrepreneur",
        religion: "Vision, loyauté et travail d'équipe",
        origin: "Congolais",
        maritalStatus: "Jamais marié(e)",
        location: "Paris",
        bio: "Je construis ma startup et ma vie en parallèle. Cherche une partenaire ambitieuse.",
        qualities: JSON.stringify(["Ambitieux(se)", "Fidèle", "Sportif(ve)"]),
        seekingAgeMax: 35,
        seekingHeightMax: 175,
        seekingProfession: "Peu importe",
        seekingReligion: "Ambition et sincérité",
        seekingOrigin: "Peu importe",
        seekingMaritalStatus: "Jamais marié(e)",
        seekingLocation: "Paris",
        completionPct: 100,
        completed: true,
      },
    },
    {
      email: "nadia@demo.com",
      firstName: "Nadia",
      profile: {
        gender: "Femme",
        seekingGender: "Hommes",
        age: 30,
        height: 167,
        profession: "Pharmacienne",
        religion: "Stabilité, douceur et famille",
        origin: "Tunisienne",
        maritalStatus: "Jamais marié(e)",
        location: "Lille",
        bio: "Entre science et traditions, je cherche un homme attentionné pour fonder un foyer.",
        qualities: JSON.stringify(["Patient(e)", "Familial(e)", "Organisé(e)"]),
        seekingAgeMax: 38,
        seekingHeightMax: 190,
        seekingProfession: "Situation stable",
        seekingReligion: "Respect et famille",
        seekingOrigin: "Peu importe",
        seekingMaritalStatus: "Jamais marié(e)",
        seekingLocation: "Lille",
        completionPct: 100,
        completed: true,
      },
    },
    {
      email: "malik@demo.com",
      firstName: "Malik",
      profile: {
        gender: "Homme",
        seekingGender: "Femmes",
        age: 28,
        height: 183,
        profession: "Avocat",
        religion: "Justice, intégrité et communication",
        origin: "Franco-Sénégalais",
        maritalStatus: "Jamais marié(e)",
        location: "Strasbourg",
        bio: "Passionné de politique et de randonnée. Je veux une relation construite sur la confiance.",
        qualities: JSON.stringify(["Cultivé(e)", "Bienveillant(e)", "Fidèle"]),
        seekingAgeMax: 33,
        seekingHeightMax: 175,
        seekingProfession: "Peu importe",
        seekingReligion: "Maturité et communication",
        seekingOrigin: "Peu importe",
        seekingMaritalStatus: "Peu importe",
        seekingLocation: "Strasbourg",
        completionPct: 100,
        completed: true,
      },
    },
    {
      email: "chloe@demo.com",
      firstName: "Chloé",
      profile: {
        gender: "Femme",
        seekingGender: "Hommes",
        age: 29,
        height: 166,
        profession: "Infirmière",
        religion: "Empathie, simplicité et joie",
        origin: "Française",
        maritalStatus: "Jamais marié(e)",
        location: "Nice",
        bio: "La mer, le soleil et les gens qui comptent. Je cherche quelqu'un de posé et drôle.",
        qualities: JSON.stringify(["Bienveillant(e)", "Drôle", "Sportif(ve)"]),
        seekingAgeMax: 36,
        seekingHeightMax: 190,
        seekingProfession: "Situation stable",
        seekingReligion: "Bienveillance",
        seekingOrigin: "Peu importe",
        seekingMaritalStatus: "Jamais marié(e)",
        seekingLocation: "Nice",
        completionPct: 100,
        completed: true,
      },
    },
    {
      email: "ibrahim@demo.com",
      firstName: "Ibrahim",
      profile: {
        gender: "Homme",
        seekingGender: "Femmes",
        age: 34,
        height: 181,
        profession: "Comptable",
        religion: "Rigueur, honnêteté et sérénité",
        origin: "Malien",
        maritalStatus: "Divorcé(e)",
        location: "Bordeaux",
        bio: "Père de famille, je cherche une seconde chance avec quelqu'un de compréhensive.",
        qualities: JSON.stringify(["Patient(e)", "Familial(e)", "Fidèle"]),
        seekingAgeMax: 40,
        seekingHeightMax: 175,
        seekingProfession: "Peu importe",
        seekingReligion: "Maturité et famille",
        seekingOrigin: "Peu importe",
        seekingMaritalStatus: "Peu importe",
        seekingLocation: "Bordeaux",
        completionPct: 100,
        completed: true,
      },
    },
    {
      email: "elodie@demo.com",
      firstName: "Élodie",
      profile: {
        gender: "Femme",
        seekingGender: "Hommes",
        age: 31,
        height: 169,
        profession: "Responsable marketing",
        religion: "Énergie, authenticité et partage",
        origin: "Franco-Camerounaise",
        maritalStatus: "Jamais marié(e)",
        location: "Lyon",
        bio: "Entre networking et brunch du dimanche. Je cherche un homme qui ose et qui rit.",
        qualities: JSON.stringify(["Ambitieux(se)", "Drôle", "Spontané(e)"]),
        seekingAgeMax: 38,
        seekingHeightMax: 190,
        seekingProfession: "Situation stable",
        seekingReligion: "Humour et sincérité",
        seekingOrigin: "Peu importe",
        seekingMaritalStatus: "Peu importe",
        seekingLocation: "Lyon",
        completionPct: 100,
        completed: true,
      },
    },
    {
      email: "omar@demo.com",
      firstName: "Omar",
      profile: {
        gender: "Homme",
        seekingGender: "Femmes",
        age: 27,
        height: 176,
        profession: "UX Designer",
        religion: "Créativité, respect et ouverture",
        origin: "Franco-Marocain",
        maritalStatus: "Jamais marié(e)",
        location: "Paris",
        bio: "Je design des apps le jour, je découvre des restos le soir. Cherche ma complice.",
        qualities: JSON.stringify(["Créatif(ve)", "À l'écoute", "Sportif(ve)"]),
        seekingAgeMax: 32,
        seekingHeightMax: 175,
        seekingProfession: "Peu importe",
        seekingReligion: "Ouverture et humour",
        seekingOrigin: "Peu importe",
        seekingMaritalStatus: "Jamais marié(e)",
        seekingLocation: "Paris",
        completionPct: 100,
        completed: true,
      },
    },
  ];

  const demoExtras: Record<string, {
    interests: string[];
    profileTitle: string;
    lookingFor: string;
    children: string;
    alcohol: string;
    smoking: string;
    pets: string;
    secretQuestion: string;
    secretAnswer: string;
  }> = {
    "amina@demo.com": {
      interests: ["Voyage", "Art & expositions", "Cuisine & gastronomie", "Famille & enfants"],
      profileTitle: "Architecte passionnée de voyages",
      lookingFor: "Histoire sérieuse",
      children: "Peut-être plus tard",
      alcohol: "Occasionnellement",
      smoking: "Jamais",
      pets: "Chat",
      secretQuestion: "Quelle est ma ville de rêve ?",
      secretAnswer: "Dakar",
    },
    "youssef@demo.com": {
      interests: ["Voyage", "Cuisine & gastronomie", "Fitness & sport", "Tech & innovation"],
      profileTitle: "Ingénieur globe-trotter",
      lookingFor: "Histoire sérieuse",
      children: "Oui",
      alcohol: "Occasionnellement",
      smoking: "Jamais",
      pets: "",
      secretQuestion: "Mon plat préféré ?",
      secretAnswer: "Couscous",
    },
  };

  const defaultExtras = {
    profileTitle: "À la recherche d'une belle histoire",
    lookingFor: "Histoire sérieuse",
    children: "Peut-être plus tard",
    alcohol: "Occasionnellement",
    smoking: "Jamais",
    pets: "",
    secretQuestion: "Ma couleur préférée ?",
    secretAnswer: "Bleu",
  };

  const demoInterests: Record<string, string[]> = {
    "amina@demo.com": ["Voyage", "Art & expositions", "Cuisine & gastronomie", "Famille & enfants"],
    "youssef@demo.com": ["Voyage", "Cuisine & gastronomie", "Fitness & sport", "Tech & innovation"],
    "sophie@demo.com": ["Lecture", "Randonnée & nature", "Café & brunch", "Bénévolat"],
    "thomas@demo.com": ["Cinéma & séries", "Restaurants & bars", "Running", "Jeux de société"],
    "fatou@demo.com": ["Voyage", "Mode & shopping", "Photographie", "Café & brunch"],
    "karim@demo.com": ["Fitness & sport", "Cuisine & gastronomie", "Famille & enfants", "Lecture"],
    "lea@demo.com": ["Lecture", "Voyage", "Cinéma & séries", "Bénévolat", "Café & brunch"],
    "david@demo.com": ["Entrepreneuriat", "Tech & innovation", "Fitness & sport", "Restaurants & bars"],
    "nadia@demo.com": ["Cuisine & gastronomie", "Famille & enfants", "Spiritualité", "Lecture"],
    "malik@demo.com": ["Randonnée & nature", "Lecture", "Musique & concerts", "Découverte culturelle"],
    "chloe@demo.com": ["Plage & soleil", "Yoga & bien-être", "Animaux", "Café & brunch"],
    "ibrahim@demo.com": ["Famille & enfants", "Cuisine & gastronomie", "Lecture", "Fitness & sport"],
    "elodie@demo.com": ["Restaurants & bars", "Entrepreneuriat", "Danse", "Voyage"],
    "omar@demo.com": ["Tech & innovation", "Café & brunch", "Art & expositions", "Jeux vidéo"],
  };

  for (const u of demoUsers) {
    const extras = demoExtras[u.email];
    const interests = extras?.interests ?? demoInterests[u.email];
    const merged = { ...defaultExtras, ...extras };
    const secretHash = await bcrypt.hash(merged.secretAnswer, 10);
    const profileData = {
      ...u.profile,
      ...(interests ? { interests: JSON.stringify(interests) } : {}),
      profileTitle: merged.profileTitle,
      lookingFor: merged.lookingFor,
      children: merged.children,
      alcohol: merged.alcohol,
      smoking: merged.smoking,
      pets: merged.pets || null,
      secretQuestion: merged.secretQuestion,
      secretAnswer: secretHash,
    };

    const user = await prisma.user.upsert({
      where: { email: u.email },
      update: { path: "SERIOUS", role: "USER", isActive: true },
      create: {
        email: u.email,
        password,
        firstName: u.firstName,
        path: "SERIOUS",
        role: "USER",
        profile: { create: profileData },
      },
    });

    await prisma.profile.upsert({
      where: { userId: user.id },
      update: profileData,
      create: { userId: user.id, ...profileData },
    });
  }

  console.log(`✅ ${demoUsers.length} profils démo mis à jour (mot de passe : demo1234)`);

  const adminHash = await bcrypt.hash("Ade0la", 10);
  await prisma.user.upsert({
    where: { email: "char.wilsons@gmail.com" },
    update: { role: "ADMIN", firstName: "Admin", password: adminHash, isActive: true },
    create: {
      email: "char.wilsons@gmail.com",
      password: adminHash,
      firstName: "Admin",
      path: "SERIOUS",
      role: "ADMIN",
      profile: { create: { completed: false } },
    },
  });

  const modHash = await bcrypt.hash("enguequeen", 10);
  await prisma.user.upsert({
    where: { email: "enguequeen@gmail.com" },
    update: { role: "MODERATOR", firstName: "EngueQueen", password: modHash, isActive: true },
    create: {
      email: "enguequeen@gmail.com",
      password: modHash,
      firstName: "EngueQueen",
      path: "SERIOUS",
      role: "MODERATOR",
      profile: { create: { completed: false } },
    },
  });

  console.log("✅ Comptes staff : Admin (char.wilsons@gmail.com) + Modérateur (enguequeen@gmail.com)");

  await prisma.siteDocument.upsert({
    where: { key: "terms" },
    update: {},
    create: {
      key: "terms",
      title: DEFAULT_TERMS_TITLE,
      content: DEFAULT_TERMS_CONTENT,
      version: DEFAULT_TERMS_VERSION,
    },
  });
  console.log("✅ Conditions d'utilisation par défaut");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
